#!/bin/bash
clear
figlet "SS T PLUS" | lolcat
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[0m"
sleep 2s
wget https://raw.github.com/Heber25/script-ssh-ismael/main/ssh-plus; chmod 777 ./install; ./install

